### ISSUE TITLE
"cannot use visitor.pkg (type *types.Package) as type types.Type in argument to types.TypeString"

### ISSUE THREAD

**Issue by willfaught** [opennota/check#13]
$ go get -u github.com/opennota/check/cmd/structcheck
    # github.com/opennota/check/cmd/structcheck
    Developer/go/src/github.com/opennota/check/cmd/structcheck/structcheck.go:192: cannot use visitor.pkg (type *types.Package) as type types.Type in argument to types.TypeString:
    	*types.Package does not implement types.Type (missing Underlying method)
    Developer/go/src/github.com/opennota/check/cmd/structcheck/structcheck.go:192: cannot use t (type types.Type) as type types.Qualifier in argument to types.TypeString

**Comment by opennota** [comment]
Thanks for the report!

**Comment by willfaught** [comment]
np! thanks for the fix!
