### ISSUE TITLE
Ignore defercheck warning if defer() is inside a function that is go() ran

### ISSUE THREAD

**Issue by cep21** [opennota/check#21]
I have code like:

```
for _, chil := range c {
  wg.Add(1)
  go func(chil string) {
    defer wg.Done()
    // ...
  }
}
```

A reasonable optimization for defercheck is to ignore defer inside for loop if it is between a go ```func(){}``` call.

**Comment by opennota** [comment]
defercheck is broken. I wouldn't recommend to use it until it is rewritten (probably never). It isn't of much help anyway.
