### ISSUE TITLE
aligncheck does not support build tags

### ISSUE THREAD

**Issue by cep21** [opennota/check#24]
Note: The field http.Request.Cancel was added in go1.5 and does not exist in go 1.4

I have two versions of code that are gated on build flags for a version of go.  Aligncheck checks both versions.  The command `aligncheck .` should skip running on files that aren't for the current build env.

```
< aligncheck .
cancel15.go:11:2: invalid operation: req (variable of type *net/http.Request) has no field or method Cancel
2015/12/15 16:36:36 could not type check: couldn't load packages due to errors:
```

The file looks like this:

```
// +build go1.5

package sfxclient

import (
    "golang.org/x/net/context"
    "net/http"
)

func (h *HTTPDatapointSink) withCancel(ctx context.Context, req *http.Request) (err error) {
    req.Cancel = ctx.Done()
    return h.handleResponse(h.Client.Do(req))
}
```

**Comment by opennota** [comment]
It's not aligncheck's fault. It's either a problem with x/tools/go/loader package, or with the Go core library (there are several open issues regarding build tags). Whatever the case, I'm thinking of deprecating aligncheck in favor of [maligned](https://github.com/mdempsky/maligned/), which is more precise. It also uses x/tools/go/loader though, so it probably has the same problem.

**Comment by gaillard** [comment]
also build tags are sometimes necessary that are not implicit like +darwin or something.
