### ISSUE TITLE
Panic at execution

### ISSUE THREAD

**Issue by bclermont** [opennota/check#39]
I don't know which input caused this

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x5cc235]

goroutine 1 [running]:
main.main()
/go/src/github.com/opennota/check/cmd/structcheck/structcheck.go:203 +0x805
```

**Comment by opennota** [comment]
> I don't know which input caused this

How is that?

**Comment by bclermont** [comment]
I mean I don't know which one of the file in my sandbox triggered this :)

**Comment by opennota** [comment]
I can't properly fix it without knowing the cause.

**Comment by bclermont** [comment]
https://github.com/opennota/check/blob/master/cmd/structcheck/structcheck.go#L203

sometimes either `program.Fset` is `nil`

Or `field` is `nil`
which can happens: https://golang.org/src/go/types/lookup.go#L25

**Comment by opennota** [comment]
*That* I understand. I don't understand the underlying cause. It would be easy to just check for nil and say, OK, that's it. But it would not be the correct fix.

**Comment by bclermont** [comment]
the codebase is huge, I can't share it, as there is a lot of proprietary code there.

is there a way to make it verbose and see which file, package struct cause this?

**Comment by opennota** [comment]
Update structcheck (`go get -u github.com/opennota/check/cmd/structcheck`) and check the sources (`structcheck package/...`).

It should now print an error about the unknown field. Grep `unknown field or method`.

**Comment by bclermont** [comment]
It don't panic anymore

Bug caused by generated code by https://github.com/therecipe/qt/
