### ISSUE TITLE
varcheck and structcheck return "could not load packages: packages not found"

### ISSUE THREAD

**Issue by Dieterbe** [opennota/check#44]
Hello, first of all thanks for the nice tools. Been using them for a while and they've proven useful.

as of recently they broke though
seems likely due to the recent package loader change:
https://github.com/opennota/check/commit/b43223f80369893b298c7cda1da077d015a28d86

we just run varcheck and structcheck in our source repo check out
(https://github.com/grafana/metrictank)
and they return 
```
2018/08/14 22:47:45 could not load packages: packages not found
```

**Comment by opennota** [comment]
`varcheck github.com/grafana/metrictank` does indeed print "could not load packages: packages not found". But there are no `.go` files in the project's root directory anyway. When I run `varcheck github.com/grafana/metrictank/...`, there are no errors.

**Comment by Dieterbe** [comment]
ok i feel silly now :) my invocation style was wrong. perhaps the previous loader wasn't so strict about it
thanks for your help!
