### ISSUE TITLE
Upstream change breaks check

### ISSUE THREAD

**Issue by konradreiche** [opennota/check#45]
```
# github.com/opennota/check/cmd/structcheck
../../opennota/check/cmd/structcheck/structcheck.go:159:8: unknown field 'Flags' in struct literal of type packages.Config
```

This seems to be due to an upstream change in the package `olang.org/x/tools/go/packages` where the field `Flags` has been renamed to `BuildFlags`.

**Comment by opennota** [comment]
Fixed in https://github.com/opennota/check/pull/46
