### ISSUE TITLE
structcheck reporting unused variables when used in test

### ISSUE THREAD

**Issue by tylerb** [opennota/check#9]
A struct var that is used in a test will be flagged as not being used. See https://github.com/tylerb/structcheck-proof

**Comment by opennota** [comment]
What's the point in having a field that is used by a test code only?

**Comment by tylerb** [comment]
It is populated directly via unmarshal and saved to a database. Test code verifies that it is populated properly. Clients use other REST calls to retrieve it.

**Comment by opennota** [comment]
Now structcheck has the `-t` option, that tells it to load test code too.

**Comment by tylerb** [comment]
Thank you!
